apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.collector.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
