namespace: external-secrets-operator
globalClusterSecretStoreName: platform-secrets
subscription:
  name: external-secrets-operator
  packageName: external-secrets-operator
  channel: stable
  installPlanApproval: Manual
  source: community-operators
  sourceNamespace: openshift-marketplace
operatorGroup:
  name: external-secrets-operator
  targetNamespaces: []
