{{- range $ns := .Values.namespaces }}
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: {{ $ns.name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    {{- with $ns.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- with $ns.labels }}
  labels:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if or $ns.displayName $ns.description $ns.nodeSelector }}
  {{- with $ns.displayName }}
  displayName: {{ . | quote }}
  {{- end }}
  {{- with $ns.description }}
  description: {{ . | quote }}
  {{- end }}
  {{- with $ns.nodeSelector }}
  nodeSelector: {{ . | quote }}
  {{- end }}
  {{- else }}
  {}
  {{- end }}
{{- end }}
