{{- if .Values.tenantGitOps.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.tenantGitOps.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "32"
  labels:
    openshift.io/cluster-monitoring: "true"
{{- end }}
