{{- if .Values.tenantGitOps.enabled }}
{{- range $tenant := .Values.tenantGitOps.tenants }}
{{- if $tenant.enabled }}
{{- $projectName := default $tenant.name $tenant.projectName }}
{{- range $repo := $tenant.repoCredentials }}
{{- $secretStoreRef := default (dict) $repo.externalSecret.secretStoreRef }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $repo.externalSecret.name }}
  namespace: {{ $.Values.tenantGitOps.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "34"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ default "1h" $repo.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ default $.Values.tenantGitOps.globalSecretStoreRef.name $secretStoreRef.name }}
    kind: {{ default $.Values.tenantGitOps.globalSecretStoreRef.kind $secretStoreRef.kind }}
  target:
    name: {{ default $repo.name $repo.externalSecret.targetName }}
    creationPolicy: {{ default "Owner" $repo.externalSecret.creationPolicy }}
    deletionPolicy: {{ default "Retain" $repo.externalSecret.deletionPolicy }}
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        name: {{ $repo.name | quote }}
        project: {{ $projectName | quote }}
        type: {{ default "git" $repo.type | quote }}
        url: {{ $repo.url | quote }}
        {{- if eq (default "https" $repo.authType) "ssh" }}
        sshPrivateKey: '{{ "{{ .sshPrivateKey }}" }}'
        {{- else }}
        username: '{{ "{{ .username }}" }}'
        password: '{{ "{{ .password }}" }}'
        {{- end }}
        {{- if $repo.insecure }}
        insecure: "true"
        {{- end }}
        {{- if $repo.enableOCI }}
        enableOCI: "true"
        {{- end }}
  {{- with $repo.externalSecret.data }}
  data:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with $repo.externalSecret.dataFrom }}
  dataFrom:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
