{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | quote }}
spec:
  destination:
    namespace: {{ .namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ .path }}
    repoURL: {{ $.Values.git.repoURL }}
    targetRevision: {{ $.Values.git.targetRevision }}
    {{- if .helmValues }}
    helm:
      values: |
{{ .helmValues | indent 8 }}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}

