apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: collector-token
  namespace: openshift-logging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: collector-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/platform/logging/default-forwarder
        property: token

# AWS Secrets Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: collector-token
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: collector-token
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: platform/logging/default-forwarder
#         property: token

# Azure Key Vault
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: collector-token
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: collector-token
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: platform-logging-default-forwarder-token

# Google Secret Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: collector-token
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: collector-token
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: platform-logging-default-forwarder
#         property: token

# IBM Cloud Secrets Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: collector-token
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: collector-token
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: arbitrary/platform-logging-default-forwarder
#         property: payload

# CyberArk Conjur
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: collector-token
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: collector-token
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: data/platform/logging/default-forwarder/token
