globalSecretStoreRef:
  name: platform-secrets
  kind: ClusterSecretStore

externalSecrets:
  - name: collector-token
    refreshInterval: 1h
    target:
      name: collector-token
      creationPolicy: Owner
    data:
      - secretKey: token
        remoteRef:
          key: platform/logging/default-forwarder
          property: token

forwarding:
  enable: true
  name: default-forwarder
  type: splunk
  url: https://logs.example.com:8088/services/collector
  secretName: collector-token
  splunk:
    indexName: openshift

# HashiCorp Vault
# externalSecrets:
#   - name: collector-token
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: collector-token
#       creationPolicy: Owner
#     data:
#       - secretKey: token
#         remoteRef:
#           key: secret/data/platform/logging/default-forwarder
#           property: token

# Azure Key Vault
# externalSecrets:
#   - name: collector-token
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: collector-token
#       creationPolicy: Owner
#     data:
#       - secretKey: token
#         remoteRef:
#           key: platform-logging-default-forwarder-token

# Google Secret Manager
# externalSecrets:
#   - name: collector-token
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: collector-token
#       creationPolicy: Owner
#     data:
#       - secretKey: token
#         remoteRef:
#           key: platform-logging-default-forwarder
#           property: token

# IBM Cloud Secrets Manager
# externalSecrets:
#   - name: collector-token
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: collector-token
#       creationPolicy: Owner
#     data:
#       - secretKey: token
#         remoteRef:
#           key: arbitrary/platform-logging-default-forwarder
#           property: payload

# CyberArk Conjur
# externalSecrets:
#   - name: collector-token
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: collector-token
#       creationPolicy: Owner
#     data:
#       - secretKey: token
#         remoteRef:
#           key: data/platform/logging/default-forwarder/token
