apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-client-secret
  namespace: openshift-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: oauth-client-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: platform/identity/example-oidc
        property: clientSecret

# HashiCorp Vault
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: oauth-client-secret
#   namespace: openshift-config
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: oauth-client-secret
#     creationPolicy: Owner
#   data:
#     - secretKey: clientSecret
#       remoteRef:
#         key: secret/data/platform/identity/example-oidc
#         property: clientSecret

# Azure Key Vault
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: oauth-client-secret
#   namespace: openshift-config
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: oauth-client-secret
#     creationPolicy: Owner
#   data:
#     - secretKey: clientSecret
#       remoteRef:
#         key: platform-identity-example-oidc-client-secret

# Google Secret Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: oauth-client-secret
#   namespace: openshift-config
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: oauth-client-secret
#     creationPolicy: Owner
#   data:
#     - secretKey: clientSecret
#       remoteRef:
#         key: platform-identity-example-oidc
#         property: clientSecret

# IBM Cloud Secrets Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: oauth-client-secret
#   namespace: openshift-config
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: oauth-client-secret
#     creationPolicy: Owner
#   data:
#     - secretKey: clientSecret
#       remoteRef:
#         key: arbitrary/platform-identity-example-oidc
#         property: payload

# CyberArk Conjur
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: oauth-client-secret
#   namespace: openshift-config
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: oauth-client-secret
#     creationPolicy: Owner
#   data:
#     - secretKey: clientSecret
#       remoteRef:
#         key: data/platform/identity/example-oidc/clientSecret
