apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: splunk-hec-token
  namespace: openshift-logging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: splunk-hec-token
    creationPolicy: Owner
  data:
    - secretKey: hecToken
      remoteRef:
        key: platform/logging/splunk
        property: hecToken

# HashiCorp Vault
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: splunk-hec-token
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: splunk-hec-token
#     creationPolicy: Owner
#   data:
#     - secretKey: hecToken
#       remoteRef:
#         key: secret/data/platform/logging/splunk
#         property: hecToken

# Azure Key Vault
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: splunk-hec-token
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: splunk-hec-token
#     creationPolicy: Owner
#   data:
#     - secretKey: hecToken
#       remoteRef:
#         key: platform-logging-splunk-hec-token

# Google Secret Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: splunk-hec-token
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: splunk-hec-token
#     creationPolicy: Owner
#   data:
#     - secretKey: hecToken
#       remoteRef:
#         key: platform-logging-splunk
#         property: hecToken

# IBM Cloud Secrets Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: splunk-hec-token
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: splunk-hec-token
#     creationPolicy: Owner
#   data:
#     - secretKey: hecToken
#       remoteRef:
#         key: arbitrary/platform-logging-splunk
#         property: payload

# CyberArk Conjur
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: splunk-hec-token
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: splunk-hec-token
#     creationPolicy: Owner
#   data:
#     - secretKey: hecToken
#       remoteRef:
#         key: data/platform/logging/splunk/hecToken
