globalSecretStoreRef:
  name: platform-secrets
  kind: ClusterSecretStore

externalSecrets:
  - name: splunk-hec-token
    refreshInterval: 1h
    target:
      name: splunk-hec-token
      creationPolicy: Owner
    data:
      - secretKey: hecToken
        remoteRef:
          key: secret/data/platform/logging/splunk
          property: hecToken

output:
  name: splunk-hec
  url: https://logs.example.com:8088/services/collector
  secretName: splunk-hec-token
  secretKey: hecToken
  index: openshift
  source: openshift
  sourcetype: _json

# AWS Secrets Manager
# externalSecrets:
#   - name: splunk-hec-token
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: splunk-hec-token
#       creationPolicy: Owner
#     data:
#       - secretKey: hecToken
#         remoteRef:
#           key: platform/logging/splunk
#           property: hecToken

# Azure Key Vault
# externalSecrets:
#   - name: splunk-hec-token
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: splunk-hec-token
#       creationPolicy: Owner
#     data:
#       - secretKey: hecToken
#         remoteRef:
#           key: platform-logging-splunk-hec-token

# Google Secret Manager
# externalSecrets:
#   - name: splunk-hec-token
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: splunk-hec-token
#       creationPolicy: Owner
#     data:
#       - secretKey: hecToken
#         remoteRef:
#           key: platform-logging-splunk
#           property: hecToken

# IBM Cloud Secrets Manager
# externalSecrets:
#   - name: splunk-hec-token
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: splunk-hec-token
#       creationPolicy: Owner
#     data:
#       - secretKey: hecToken
#         remoteRef:
#           key: arbitrary/platform-logging-splunk
#           property: payload

# CyberArk Conjur
# externalSecrets:
#   - name: splunk-hec-token
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: splunk-hec-token
#       creationPolicy: Owner
#     data:
#       - secretKey: hecToken
#         remoteRef:
#           key: data/platform/logging/splunk/hecToken
