class_name: dev
environment: dev
openshift_version: "4.20"
private_cluster: true
multi_az: true
enable_acm_registration: false
enable_gitops_bootstrap: true
machine_pools:
  - name: system
    profile: system
    replicas: 2
    autoscaling:
      enabled: true
      min_replicas: 2
      max_replicas: 4
