class_name: prod
environment: prod
openshift_version: "4.20"
private_cluster: true
multi_az: true
enable_acm_registration: false
enable_gitops_bootstrap: true
machine_pools:
  - name: system
    profile: system
    replicas: 3
    autoscaling:
      enabled: true
      min_replicas: 3
      max_replicas: 6
  - name: observability
    profile: observability
    replicas: 3
    autoscaling:
      enabled: true
      min_replicas: 3
      max_replicas: 6
