apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-remote-write
  namespace: openshift-user-workload-monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: prometheus-remote-write
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/platform/monitoring/remote-write
        property: token

# AWS Secrets Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: prometheus-remote-write
#   namespace: openshift-user-workload-monitoring
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: prometheus-remote-write
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: platform/monitoring/remote-write
#         property: token

# Azure Key Vault
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: prometheus-remote-write
#   namespace: openshift-user-workload-monitoring
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: prometheus-remote-write
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: platform-monitoring-remote-write-token

# Google Secret Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: prometheus-remote-write
#   namespace: openshift-user-workload-monitoring
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: prometheus-remote-write
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: platform-monitoring-remote-write
#         property: token

# IBM Cloud Secrets Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: prometheus-remote-write
#   namespace: openshift-user-workload-monitoring
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: prometheus-remote-write
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: arbitrary/platform-monitoring-remote-write
#         property: payload

# CyberArk Conjur
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: prometheus-remote-write
#   namespace: openshift-user-workload-monitoring
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: prometheus-remote-write
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: data/platform/monitoring/remote-write/token
