{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ default $.Values.namespace .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ default "1h" .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreRef.name }}
    kind: {{ default "ClusterSecretStore" .secretStoreRef.kind }}
  target:
    name: {{ .target.name }}
    creationPolicy: {{ default "Owner" .target.creationPolicy }}
    deletionPolicy: {{ default "Retain" .target.deletionPolicy }}
    {{- with .target.template }}
    template:
{{ toYaml . | indent 6 }}
    {{- end }}
  {{- with .data }}
  data:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .dataFrom }}
  dataFrom:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
