apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
data:
  config.yaml: |-
    enableUserWorkload: {{ .Values.clusterMonitoring.enableUserWorkload }}
    alertmanagerMain:
      enableUserAlertmanagerConfig: {{ .Values.clusterMonitoring.alertmanagerMain.enableUserAlertmanagerConfig }}

