apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloud-credentials
  namespace: openshift-adp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: cloud-credentials
    creationPolicy: Owner
  data:
    - secretKey: cloud
      remoteRef:
        key: platform/oadp/cloud-credentials
        property: cloud

# HashiCorp Vault
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: cloud-credentials
#   namespace: openshift-adp
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: cloud-credentials
#     creationPolicy: Owner
#   data:
#     - secretKey: cloud
#       remoteRef:
#         key: secret/data/platform/oadp/cloud-credentials
#         property: cloud

# Azure Key Vault
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: cloud-credentials
#   namespace: openshift-adp
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: cloud-credentials
#     creationPolicy: Owner
#   data:
#     - secretKey: cloud
#       remoteRef:
#         key: platform-oadp-cloud-credentials

# Google Secret Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: cloud-credentials
#   namespace: openshift-adp
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: cloud-credentials
#     creationPolicy: Owner
#   data:
#     - secretKey: cloud
#       remoteRef:
#         key: platform-oadp-cloud-credentials
#         property: cloud

# IBM Cloud Secrets Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: cloud-credentials
#   namespace: openshift-adp
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: cloud-credentials
#     creationPolicy: Owner
#   data:
#     - secretKey: cloud
#       remoteRef:
#         key: arbitrary/platform-oadp-cloud-credentials
#         property: payload

# CyberArk Conjur
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: cloud-credentials
#   namespace: openshift-adp
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: platform-secrets
#     kind: ClusterSecretStore
#   target:
#     name: cloud-credentials
#     creationPolicy: Owner
#   data:
#     - secretKey: cloud
#       remoteRef:
#         key: data/platform/oadp/cloud-credentials
