globalSecretStoreRef:
  name: platform-secrets
  kind: ClusterSecretStore

enableDataProtectionApplication: true

externalSecrets:
  - name: cloud-credentials
    refreshInterval: 1h
    target:
      name: cloud-credentials
      creationPolicy: Owner
    data:
      - secretKey: cloud
        remoteRef:
          key: platform/oadp/cloud-credentials
          property: cloud

backupLocation:
  provider: aws
  bucket: example-backups
  region: us-east-2
  credentialSecret: cloud-credentials
  credentialKey: cloud

snapshotLocation:
  provider: aws
  region: us-east-2
  credentialSecret: cloud-credentials
  credentialKey: cloud

# HashiCorp Vault
# externalSecrets:
#   - name: cloud-credentials
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: cloud-credentials
#       creationPolicy: Owner
#     data:
#       - secretKey: cloud
#         remoteRef:
#           key: secret/data/platform/oadp/cloud-credentials
#           property: cloud

# Azure Key Vault
# externalSecrets:
#   - name: cloud-credentials
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: cloud-credentials
#       creationPolicy: Owner
#     data:
#       - secretKey: cloud
#         remoteRef:
#           key: platform-oadp-cloud-credentials

# Google Secret Manager
# externalSecrets:
#   - name: cloud-credentials
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: cloud-credentials
#       creationPolicy: Owner
#     data:
#       - secretKey: cloud
#         remoteRef:
#           key: platform-oadp-cloud-credentials
#           property: cloud

# IBM Cloud Secrets Manager
# externalSecrets:
#   - name: cloud-credentials
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: cloud-credentials
#       creationPolicy: Owner
#     data:
#       - secretKey: cloud
#         remoteRef:
#           key: arbitrary/platform-oadp-cloud-credentials
#           property: payload

# CyberArk Conjur
# externalSecrets:
#   - name: cloud-credentials
#     refreshInterval: 1h
#     secretStoreRef:
#     target:
#       name: cloud-credentials
#       creationPolicy: Owner
#     data:
#       - secretKey: cloud
#         remoteRef:
#           key: data/platform/oadp/cloud-credentials
