apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: platform-secrets
spec:
  provider:
    azurekv:
      vaultUrl: https://example-kv.vault.azure.net
      tenantId: 00000000-0000-0000-0000-000000000000
      authType: WorkloadIdentity
      serviceAccountRef:
        name: eso-azure
        namespace: external-secrets-operator
