apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-consumer-secret
  namespace: openshift-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  target:
    name: oauth-client-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: platform/identity/oauth-client
        property: clientSecret
