apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: platform-secrets
spec:
  provider:
    conjur:
      url: https://conjur.example.com
      account: conjur
      auth:
        jwt:
          account: conjur
          serviceID: eso-jwt-auth
          serviceAccountRef:
            name: eso-conjur
            namespace: external-secrets-operator
            audiences:
              - https://conjur.example.com
