apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: platform-secrets
spec:
  provider:
    gcpsm:
      projectID: example-project
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: eso-gcp
            namespace: external-secrets-operator
