apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: platform-secrets
spec:
  provider:
    ibm:
      serviceUrl: https://<SECRETS_MANAGER_ID>.<REGION>.secrets-manager.appdomain.cloud
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-secrets-manager-api-key
            namespace: external-secrets-operator
            key: apiKey
