{{- range $sa := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name }}
  namespace: {{ $sa.namespace }}
  {{- with $sa.labels }}
  labels:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with $sa.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- if hasKey $sa "automountServiceAccountToken" }}
automountServiceAccountToken: {{ $sa.automountServiceAccountToken }}
{{- end }}
{{- with $sa.imagePullSecrets }}
imagePullSecrets:
{{- range . }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
