{{- if .Values.install.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.install.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cost-management-operatorgroup
  namespace: {{ .Values.install.namespace }}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.install.subscriptionName }}
  namespace: {{ .Values.install.namespace }}
spec:
  channel: {{ .Values.install.channel }}
  installPlanApproval: {{ .Values.install.installPlanApproval }}
  name: {{ .Values.install.packageName }}
  source: {{ .Values.install.source }}
  sourceNamespace: {{ .Values.install.sourceNamespace }}
{{- end }}
