apiVersion: samples.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  architectures:
    - x86_64
  samplesRegistry: "{{ .Values.samplesRegistry }}"

