namespace: openshift-compliance
subscription:
  name: compliance-operator
  packageName: compliance-operator
  channel: stable
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    nodeSelector:
      node-role.kubernetes.io/worker: ""
    env:
      - name: PLATFORM
        value: HyperShift
operatorGroup:
  name: compliance-operator
  targetNamespaces: []
scanSettings: []
scanSettingBindings: []
